### ISSUE TITLE
Not enough work 

### ISSUE THREAD

**Issue by MandyKarnauskas-NOAA** [Openscapes/2022-noaa-sefsc-summer#22]
I could use a few more trainings and random taskers -- can someone help? 

@imaginaryfish @CarissaGervasi-NOAA @BrittanyTroast-NOAA

**Comment by BrittanyTroast-NOAA** [comment]
There's always random tasks to do!

**Comment by MandyKarnauskas-NOAA** [comment]
- [ ] item 1
- [ ] item 2
- [ ] item 3

**Comment by imaginaryfish** [comment]
This task is finished... there's always enough work
